### PR TITLE
Extending DevCommand metadata for allowing untyped pushing of DevCommand to Commands

### PR DESCRIPTION
**Pull request by rewin123**
And fixing geting type info in traits

[RENDERED](https://github.com/rewin123/rfcs/blob/rewin123-some_extends/rfcs/77-dev-tools-abstraction.md)

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you link to your prototype in the RFC as well? Probably in the implementation details. I'd like to make it clear that this design has been proven to work.

**Comment by rewin123** [comment]
Won't it be a problem that my code is in the bad coding style a bit? I won't have time to clean it until this weekend at least.

**Comment by alice-i-cecile** [comment]
Nope, that's fine for now! All we really care about is "this basically works", not "this is ready to upstream".

**Comment by rewin123** [comment]
> Can you link to your prototype in the RFC as well? Probably in the implementation details. I'd like to make it clear that this design has been proven to work.

Added

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
